### ISSUE TITLE
Space Wolves special weapons

### ISSUE THREAD

**Issue by ebruning** [AppSynergy/shadow-war-armageddon-roster#12]
The astra_militarum.toml should be updated to reflect Space Wolves Weapons. How it is now it applies to all gunners (d'oh). 

Changing this 
```
[weapons.special.flamer]
name = "Flamer"
cost = 40
only_fighter = ["gunner"]
```

to something like this
```
[weapons.special.space_wolves.flamer]
name = "Flamer"
cost = 40
only_fighter = ["gunner"]
only_subfaction = ["space_wolves"]
```
I think this is related to #11 , I'm not sure all that needs to be updated to add sub-factions. I can look at it in the next few days

**Comment by ebruning** [comment]
Looking at the rules again, this may be ok, space marines don't have any other spacial weapons

**Comment by AppSynergy** [comment]
I'm not sure why the imperial guard list would have Space Wolves weapons in it, can you elaborate?

**Comment by ebruning** [comment]
Because I typed the wrong name its **astra_militarum.toml** not **astra_militarum.toml**. That why it's weird :)

It's a sub-faction for Space Marines, so no Novitiate Scouts and specific skills

**Comment by AppSynergy** [comment]
Space Wolves now proudly their own faction!
